language: node_js
node_js: stable
dist: trusty
sudo: false
cache:
  directories:
    - bower_components
branches:
  only:
    - master
before_script:
  - npm install -g polymer-cli
  - polymer install --variants
script:
  - polymer test -s 'default'
addons:
  jwt:
    secure: EEVIwmqo/1GYmA0cIEqGJwWSr2sRtWG320yUfP4XNGEo17Ml75MUQREl9f8UPhP/3f/RgP0twO9vs6sMQ/K2XawJLwnjjnU08s3xEjPKBZCFc93/RhChIaJz5vU8bwYaWGfR5NmRnLI3iA+tTFJBb3D71ZMjhrjuSjHnGM7v02F966Nh+PDOiqMNIEg2eH0zi9Mgurq3Z37RmCL0RAoimyeSPu0s0p5fs4TGPmRdvRy87AarM2hnSMhd6MmUwlpEgtLId6sMd1fzqE0o0X+t2GDWzwBk7dAIz4XXfIaroaOZ4h4GD//srR4RPVRDnaBujwVGFJIgUVC5yEwUVzaEtFaKtwQH6k3ACcPLHd5cmW6ys39JIa7leg9HKjmnGJqZNm4amAWGIwerjYFer9hJlQlespm7tniu2BnxBOjnjWHX2yDbi56gQOjeaRbmdaX00TrS5Q1XEXThq2j28twKF0okYiEk/Hgq/dniafFXS915vccPM38cU3h2AA7RKGKFceKLOD+DVy/ZsOkahKhFwWSo1ms9ycMJ+z3aIPprwo4XMGydmiurOeBXb5YEH1HWCGGFsjCdQVKm/js5uFpOH5iO5f3L7goIMnbB9o7dr2DEe10BSsdGoPrq1FxLuCF2qzPE+Xl/gk1E2jaLvkCq3f8so4MjDnFclmeqz5jik2k=
